swagger: "2.0"
info:
  title: GPS Viewer
  version: 0.0.1
schemes:
  - http
paths:
  "/gqs/{deviceId}":
    get:
      description: Return device gps info
      operationId: getGpsById
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: deviceId
          in: path
          required: true
          type: integer
          format: int64
          x-example: 99999
      responses:
        "200":
          description: successful operationId
          schema:
            "$ref": "#/definitions/DeviceGPS"
    post:
      description: Update a device GPS by ID
      operationId: updateGpsById
      consumes:
        - application/json
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: deviceId
          in: path
          required: true
          type: integer
          format: int64
          x-example: 99999
        - name: body
          in: body
          required: true
          schema:
            "$ref": "#/definitions/updateDeviceGPS"
      responses:
        "200":
          description: successful operation
          schema:
            "$ref": "#/definitions/DeviceGPS"
definitions:
  DeviceGPS:
    type: object
    required:
      - lat
      - lng
    properties:
      id:
        type: integer
        format: int64
        example: 99999
      lat:
        type: number
        format: double
        example: 34.69139
      lng:
        type: number
        format: double
        example: 135.18306
  updateDeviceGPS:
    type: object
    required:
      - lat
      - lng
    properties:
      lat:
        type: number
        format: double
        example: 34.69139
      lng:
        type: number
        format: double
        example: 135.18306
