swagger: "2.0"
info:
  title: GPS Viewer
  version: 0.0.1
basePath: /gps-viewer/v1
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
tags:
  - name: gps
    description: GPS情報
paths:
  "/gqs/{deviceId}":
    get:
      tags:
        - gps
      description: Return device gps info
      operationId: getGpsByDeviceId
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: deviceId
          in: path
          required: true
          type: string
          x-example: 99999
      responses:
        "200":
          description: successful operationId
          schema:
            "$ref": "#/definitions/DeviceGPS"
        "400":
          description: Bad Request
          schema:
            "$ref": "#/definitions/Error"
        "404":
          description: 当該データなし
          schema:
            "$ref": "#/definitions/Error"
        "500":
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/Error"
    post:
      tags:
        - gps
      description: Register a device GPS by ID
      operationId: registerGpsByDeviceId
      consumes:
        - application/json
      produces:
        - application/json; charset=utf-8
      parameters:
        - name: deviceId
          in: path
          required: true
          type: string
          x-example: 99999
        - name: body
          in: body
          required: true
          schema:
            "$ref": "#/definitions/registerDeviceGPS"
      responses:
        "201":
          description: successful operation
          schema:
            "$ref": "#/definitions/DeviceGPS"
        "400":
          description: Bad Request
          schema:
            "$ref": "#/definitions/Error"
        "500":
          description: Internal Server Error
          schema:
            "$ref": "#/definitions/Error"
definitions:
  DeviceGPS:
    type: object
    required:
      - deviceId
      - deviceType
      - lat
      - lng
      - recordedAt
    properties:
      deviceId:
        type: string
        example: 99999
      deviceType:
        type: string
        example: microcomputer
      lat:
        type: number
        format: double
        example: 34.69139
      lng:
        type: number
        format: double
        example: 135.18306
      recordedAt:
        type: string
        format: date-time
  registerDeviceGPS:
    type: object
    required:
      - deviceId
      - deviceType
      - lat
      - lng
      - recordedAt
    properties:
      deviceId:
        type: string
        example: 99999
      deviceType:
        type: string
        example: microcomputer
      lat:
        type: number
        format: double
        example: 34.69139
      lng:
        type: number
        format: double
        example: 135.18306
      recordedAt:
        type: string
        format: date-time
  Error:
    type: object
    properties:
      code:
        type: integer
        description: エラーコード
      message:
        type: string
        description: エラーメッセージ
